# Generated by Django 5.0.6 on 2024-06-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_fin_cnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('item_type', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=100, null=True)),
                ('hsn', models.BigIntegerField(blank=True, null=True)),
                ('sac', models.BigIntegerField(blank=True, null=True)),
                ('tax_reference', models.CharField(max_length=100, null=True)),
                ('intra_state_tax', models.IntegerField(default=0, null=True)),
                ('inter_state_tax', models.IntegerField(default=0, null=True)),
                ('sales_account', models.CharField(max_length=100, null=True)),
                ('selling_price', models.FloatField(default=0.0, null=True)),
                ('sales_description', models.CharField(max_length=100, null=True)),
                ('purchase_account', models.CharField(max_length=100, null=True)),
                ('purchase_price', models.FloatField(default=0.0, null=True)),
                ('purchase_description', models.CharField(max_length=100, null=True)),
                ('item_created', models.DateField(auto_now_add=True, null=True)),
                ('min_stock', models.IntegerField(default=0, null=True)),
                ('inventory_account', models.CharField(blank=True, max_length=100, null=True)),
                ('opening_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('current_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_in', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_out', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_unit_rate', models.FloatField(blank=True, default=0.0, null=True)),
                ('status', models.CharField(default='Active', max_length=100, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.AddField(
            model_name='fin_cnotification',
            name='Item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items'),
        ),
        migrations.CreateModel(
            name='Fin_Items_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_Items_Transaction_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('action', models.CharField(blank=True, choices=[('Created', 'Created'), ('Edited', 'Edited')], max_length=20, null=True)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
            ],
        ),
    ]
