# Generated by Django 5.0.6 on 2024-06-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0008_fin_customers_fin_customers_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_cnotification',
            name='Customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers'),
        ),
    ]
