# Generated by Django 5.0 on 2024-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0014_remove_fin_bankholder_arithmeticerrormount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_bankholder',
            name='status',
            field=models.CharField(default='Active', max_length=100, null=True),
        ),
    ]
