# Generated by Django 5.0 on 2024-06-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0015_fin_bankholder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_bankholder',
            name='Bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
