# Generated by Django 5.0 on 2024-06-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0016_alter_fin_bankholder_bank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_bankholder',
            name='Date',
        ),
        migrations.AlterField(
            model_name='fin_bankholdercomment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='fin_bankholder',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
